## Data Cleaning: the runs dataframe

In [1]:
%cd desktop\data-done-quick

C:\Users\jose\desktop\data-done-quick

In [2]:
import numpy as np
import pandas as pd
import re

In [3]:
runs = pd.read_csv('data\\runs.csv', engine = 'python')

In [4]:
runs.head()

,Description,End Time,Name,Start Time,run_id
0,NaN,07/07/2014 23:37:56 +0000,Toejam And Earl 2: Panic On Funkotron,07/07/2014 23:37:56 +0000,972.0
1,NaN,07/07/2014 23:37:56 +0000,Mega Man 3,07/07/2014 23:37:56 +0000,973.0
2,NaN,07/07/2014 23:37:56 +0000,Limbo,07/07/2014 23:37:56 +0000,974.0
3,NaN,07/07/2014 23:37:56 +0000,Rayman 2: The Great Escape,07/07/2014 23:37:56 +0000,975.0
4,NaN,07/07/2014 23:37:56 +0000,Quake 2,07/07/2014 23:37:56 +0000,976.0

In [5]:
runs.loc[runs.Name == "Super Mario World 2: Yoshi's Island"]

,Description,End Time,Name,Start Time,run_id
54,100%,01/05/2012 04:14:57 +0000,Super Mario World 2: Yoshi's Island,01/05/2012 01:00:00 +0000,866.0
239,any% donations for 100%,01/07/2013 02:55:54 +0000,Super Mario World 2: Yoshi's Island,01/07/2013 00:07:00 +0000,6.0
484,100%. Donation incentive for glitched run.,01/06/2014 22:35:00 +0000,Super Mario World 2: Yoshi's Island,01/06/2014 19:43:00 +0000,400.0
896,any% warps race,01/09/2015 02:02:00 +0000,Super Mario World 2: Yoshi's Island,01/08/2015 23:28:00 +0000,857.0
932,100%,07/26/2015 19:28:00 +0000,Super Mario World 2: Yoshi's Island,07/26/2015 16:00:00 +0000,1115.0

In [6]:
def check_title(s, title):
    try:
        return title in s
    except:
        return False

In [7]:
runs.loc[runs.Name.apply(lambda x: check_title(x, "Super Metroid"))]

,Description,End Time,Name,Start Time,run_id
5,100% racetranquilite and dessyreqt,07/07/2014 23:37:56 +0000,Super Metroid,07/07/2014 23:37:56 +0000,977.0
122,any%,01/07/2012 17:15:00 +0000,Super Metroid,01/07/2012 17:15:00 +0000,934.0
206,Dessyreqt,05/27/2012 04:18:00 +0000,Super Metroid,05/27/2012 02:33:00 +0000,1068.0
337,NaN,01/11/2013 05:34:35 +0000,Super Metroid,01/11/2013 04:45:00 +0000,93.0
431,Donate for D e e R F o r C e category,07/29/2013 04:29:55 +0000,Super Metroid,07/29/2013 03:00:00 +0000,192.0
594,race,01/11/2014 06:48:00 +0000,Super Metroid,01/11/2014 05:42:00 +0000,499.0
765,Low% run incentive for glitched any%,06/29/2014 05:32:00 +0000,Super Metroid,06/29/2014 03:47:00 +0000,674.0
928,NaN,01/11/2015 03:43:00 +0000,Super Metroid,01/11/2015 02:03:00 +0000,861.0
1090,Race!,08/02/2015 01:19:00 +0000,Super Metroid,08/02/2015 00:01:00 +0000,1281.0
1143,Bonus Incentive: Super Metroid (Any% 2p1c - Oa...,01/06/2016 00:06:41 +0000,Super Metroid Bonus Any% 2p1c,01/05/2016 22:49:40 +0000,1644.0
1247,Donation Incentive: Save or Kill the Animals,01/10/2016 04:12:14 +0000,Super Metroid Reverse Boss Order,01/10/2016 02:23:14 +0000,1744.0
1423,NaN,07/10/2016 03:22:00 +0000,Super Metroid Any%,07/10/2016 02:10:00 +0000,1935.0
1483,NaN,01/10/2017 18:31:46 +0000,Super Metroid Rotation Any%,01/10/2017 17:19:46 +0000,2004.0
1605,NaN,01/15/2017 05:28:45 +0000,Super Metroid 100%,01/15/2017 03:20:45 +0000,2119.0
1731,NaN,07/08/2017 05:00:00 +0000,Super Metroid Low% Ice Race,07/08/2017 03:50:00 +0000,2257.0
1791,NaN,09/03/2017 22:48:17 +0000,Super Metroid 100% Map Race,09/03/2017 21:14:17 +0000,2635.0
2010,NaN,06/27/2018 05:20:00 +0000,Super Metroid 100% Map Completion,06/27/2018 03:39:25 +0000,3022.0
2082,NaN,06/30/2018 04:36:00 +0000,Tasbot Plays Super Metroid 0% By Sniq And Tota...,06/30/2018 04:20:00 +0000,3097.0

## Handling missing values

In [8]:
runs.loc[~runs.Name.apply(lambda x: isinstance(x, str))]

                               Description End Time  Name Start Time  run_id
10                              8 way race     None  None       None     NaN
11   Feasel  romscout  duckfist  UltraJMan     None  None       None     NaN

In [9]:
runs.loc[runs.Name == 'Castle Crashers']

,Description,End Time,Name,Start Time,run_id
12,Zyre TheSeawolf1 Raen and UraniumAnchor,07/07/2014 23:37:57 +0000,Castle Crashers,07/07/2014 23:37:57 +0000,982.0

In [10]:
runs.count()

Description     770
End Time       2100
Name           2100
Start Time     2100
run_id         2100
dtype: int64

In [11]:
runs.dtypes

Description     object
End Time        object
Name            object
Start Time      object
run_id         float64
dtype: object

In [12]:
runs.ix[12, 'Description'] = runs.ix[10, 'Description'] + '\n' + runs.ix[11, 'Description'] + '\n' + runs.ix[12, 'Description']

C:\Users\jose\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.

In [13]:
runs.iloc[12]

Description    8 way race\n Feasel  romscout  duckfist  Ultra...
End Time                               07/07/2014 23:37:57 +0000
Name                                             Castle Crashers
Start Time                             07/07/2014 23:37:57 +0000
run_id                                                       982
Name: 12, dtype: object

In [14]:
runs = runs.drop(labels = [10, 11])

In [15]:
runs.loc[~(runs.Name.apply(lambda x: isinstance(x, str)) & runs['End Time'].apply(lambda x: isinstance(x, str)) & runs['Start Time'].apply(lambda x: isinstance(x, str)))]

Empty DataFrame
Columns: [Description, End Time, Name, Start Time, run_id]
Index: []

## Extracting run categories

In [16]:
runs['name_token'] = runs.Name.apply(lambda x: x.split(' '))

In [17]:
runs.name_token.head()

0    [Toejam, And, Earl, 2:, Panic, On, Funkotron]
1                                   [Mega, Man, 3]
2                                          [Limbo]
3                 [Rayman, 2:, The, Great, Escape]
4                                       [Quake, 2]
Name: name_token, dtype: object

In [18]:
word_hist = {}

def word_count(tokens, word_hist):
    for token in tokens:
        if token in word_hist.keys():
            word_hist[token] += 1
        else:
            word_hist[token] = 1
            
    return word_hist

In [19]:
runs.name_token.apply(lambda x: word_count(x, word_hist))

0       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
1       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
3       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
4       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
5       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
6       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
7       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
8       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
9       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
12      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
13      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
14      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
15      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
16      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
17      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
18      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
19      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
20      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
21      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
22      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
23      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
24      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
25      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
26      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
27      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
28      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
29      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
30      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
31      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
                              ...
2072    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2073    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2074    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2075    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2076    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2077    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2078    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2079    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2080    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2081    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2082    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2083    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2084    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2085    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2086    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2087    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2088    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2089    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2090    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2091    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2092    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2093    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2094    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2095    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2096    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2097    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2098    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2099    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2100    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2101    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
Name: name_token, Length: 2100, dtype: object

In [20]:
runs[runs.Name.apply(lambda x: check_title(x, 'Donkey Kong Country'))]

,Description,End Time,Name,Start Time,run_id,name_token
125,Twig,01/07/2012 17:15:00 +0000,Donkey Kong Country 2,01/07/2012 17:15:00 +0000,937.0,"[Donkey, Kong, Country, 2]"
197,Essentia,05/26/2012 22:13:00 +0000,Donkey Kong Country 2,05/26/2012 21:13:00 +0000,1059.0,"[Donkey, Kong, Country, 2]"
300,all levels race,01/09/2013 22:21:38 +0000,Donkey Kong Country,01/09/2013 21:41:00 +0000,62.0,"[Donkey, Kong, Country]"
301,NaN,01/09/2013 23:13:02 +0000,Donkey Kong Country 2,01/09/2013 22:25:00 +0000,63.0,"[Donkey, Kong, Country, 2]"
302,Any%,01/10/2013 01:03:55 +0000,Donkey Kong Country Returns,01/09/2013 23:20:00 +0000,64.0,"[Donkey, Kong, Country, Returns]"
365,any%,07/25/2013 21:57:00 +0000,Donkey Kong Country Returns,07/25/2013 20:12:00 +0000,135.0,"[Donkey, Kong, Country, Returns]"
532,101%. Donations for a glitched run,01/08/2014 23:57:00 +0000,Donkey Kong Country,01/08/2014 22:33:00 +0000,443.0,"[Donkey, Kong, Country]"
533,possible race and donation incentive for lost...,01/09/2014 00:52:00 +0000,Donkey Kong Country 2,01/08/2014 23:57:00 +0000,444.0,"[Donkey, Kong, Country, 2]"
534,any% donations for warpless,01/09/2014 01:52:00 +0000,Donkey Kong Country 3,01/09/2014 00:52:00 +0000,445.0,"[Donkey, Kong, Country, 3]"
612,All Stages,06/23/2014 00:03:00 +0000,Donkey Kong Country,06/22/2014 23:20:00 +0000,530.0,"[Donkey, Kong, Country]"
613,Race!,06/23/2014 01:01:00 +0000,Donkey Kong Country 2: Diddy's Kong Quest,06/23/2014 00:03:00 +0000,678.0,"[Donkey, Kong, Country, 2:, Diddy's, Kong, Quest]"
768,any%,01/04/2015 19:06:00 +0000,Donkey Kong Country Tropical Freeze,01/04/2015 17:00:00 +0000,708.0,"[Donkey, Kong, Country, Tropical, Freeze]"
836,4-way race,01/07/2015 01:56:00 +0000,Donkey Kong Country 2,01/07/2015 00:42:00 +0000,709.0,"[Donkey, Kong, Country, 2]"
937,All Stages race!,07/26/2015 22:52:00 +0000,Donkey Kong Country,07/26/2015 22:10:00 +0000,1120.0,"[Donkey, Kong, Country]"
939,NaN,07/27/2015 00:22:00 +0000,Donkey Kong Country 3,07/26/2015 23:19:00 +0000,1122.0,"[Donkey, Kong, Country, 3]"
1171,NaN,01/06/2016 22:07:20 +0000,Donkey Kong Country Any% All Stages,01/06/2016 21:20:10 +0000,1673.0,"[Donkey, Kong, Country, Any%, All, Stages]"
1172,NaN,01/06/2016 23:55:11 +0000,Donkey Kong Country 2: Diddy's Kong Quest 102%,01/06/2016 22:07:20 +0000,1674.0,"[Donkey, Kong, Country, 2:, Diddy's, Kong, Que..."
1255,NaN,07/04/2016 00:36:00 +0000,Donkey Kong Country: Tropical Freeze Any%,07/03/2016 22:46:00 +0000,1769.0,"[Donkey, Kong, Country:, Tropical, Freeze, Any%]"
1337,NaN,07/06/2016 21:42:00 +0000,Donkey Kong Country 3 Any%,07/06/2016 20:37:00 +0000,1850.0,"[Donkey, Kong, Country, 3, Any%]"
1583,NaN,01/14/2017 04:51:35 +0000,Donkey Kong Country Trilogy Relay Trilogy Relay,01/14/2017 02:18:35 +0000,2101.0,"[Donkey, Kong, Country, Trilogy, Relay, Trilog..."
1767,NaN,09/02/2017 18:13:47 +0000,Donkey Kong Country 2 Any%,09/02/2017 17:28:03 +0000,2612.0,"[Donkey, Kong, Country, 2, Any%]"
1817,NaN,01/08/2018 16:49:00 +0000,Donkey Kong Country 2: Diddy's Kong Quest Any%...,01/08/2018 15:35:00 +0000,2667.0,"[Donkey, Kong, Country, 2:, Diddy's, Kong, Que..."
1818,NaN,01/08/2018 17:55:00 +0000,Donkey Kong Country Reverse Boss Order,01/08/2018 16:49:00 +0000,2668.0,"[Donkey, Kong, Country, Reverse, Boss, Order]"

In [21]:
def tokenize(s):
    try:
        return s.split(' ')
    except:
        return []

In [22]:
runs['desc_token'] = runs.Description.apply(tokenize)

In [23]:
runs.desc_token.apply(lambda x: word_count(x, word_hist))

0       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
1       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
3       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
4       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
5       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
6       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
7       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
8       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
9       {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
12      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
13      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
14      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
15      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
16      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
17      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
18      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
19      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
20      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
21      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
22      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
23      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
24      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
25      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
26      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
27      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
28      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
29      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
30      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
31      {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
                              ...
2072    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2073    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2074    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2075    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2076    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2077    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2078    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2079    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2080    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2081    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2082    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2083    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2084    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2085    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2086    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2087    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2088    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2089    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2090    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2091    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2092    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2093    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2094    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2095    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2096    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2097    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2098    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2099    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2100    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
2101    {'Toejam': 4, 'And': 57, 'Earl': 4, '2:': 40, ...
Name: desc_token, Length: 2100, dtype: object

In [24]:
words = pd.DataFrame.from_dict(word_hist, orient = 'index')

In [25]:
words = words.rename(index = str, columns = {0 : 'count'})

In [26]:
words.sort_values(by = 'count', ascending = False).head(10)

       count
Any%     663
The      336
Of       253
Super    208
for      200
         187
2        163
Mario    141
All      116
Man      104

In [27]:
words['word'] = words.index

In [28]:
words.loc[['%' in s for s in words.word]].sort_values(by = 'count')

             count         word
Blooper%         1     Blooper%
Broken%          1      Broken%
marvel%          1      marvel%
glitches%        1    glitches%
101%.            1        101%.
broken%          1      broken%
Cutscenes%       1   Cutscenes%
DanielSan%       1   DanielSan%
Bee%             1         Bee%
Max%             1         Max%
artifacts%       1   artifacts%
W-Fist%          1      W-Fist%
vision%          1      vision%
Glitch%          1      Glitch%
shoutouts%       1   shoutouts%
Nemesis%;        1    Nemesis%;
any%;            1        any%;
(hardest%)       1   (hardest%)
NTA%             1         NTA%
CCH%             1         CCH%
any%.            1        any%.
Hard%            1        Hard%
Houlihan%        1    Houlihan%
Glitchless%      1  Glitchless%
(6%)             1         (6%)
Talk%            1        Talk%
Pre-Show%        1    Pre-Show%
Amy%             1         Amy%
Cutscene%        1    Cutscene%
Pacifist%        1    Pacifist%
102%             1         102%
Tasbot%          1      Tasbot%
Any%/100%        1    Any%/100%
Cleric%          1      Cleric%
low%.            1        low%.
Mania%           1       Mania%
106%             2         106%
cutscene%        2    cutscene%
1%               2           1%
%                3            %
0%               3           0%
(Any%            4        (Any%
low%             4         low%
100%.           11        100%.
Low%            11         Low%
any%            39         any%
100%            92         100%
Any%           663         Any%

In [29]:
words.loc[['less' in s for s in words.word]]

             count         word
Swordless        2    Swordless
Deathless        2    Deathless
Wingless         1     Wingless
Glitchless      17   Glitchless
Warpless        19     Warpless
Zipless          2      Zipless
(Swordless)      1  (Swordless)
Scriptless       2   Scriptless
(Warpless)       1   (Warpless)
(Zipless)        1    (Zipless)
Glitchless%      1  Glitchless%
potionless.      1  potionless.
warpless         3     warpless
warpless.        1    warpless.
Warpless.        1    Warpless.
Hoverless        1    Hoverless

In [30]:
#runs.Description = runs.Description.fillna('')

In [31]:
runs.count()

Description     768
End Time       2100
Name           2100
Start Time     2100
run_id         2100
name_token     2100
desc_token     2100
dtype: int64

In [32]:
def search_string(s, x):
    try:
        return s.lower() in x.lower()
    except:
        return False

def search(s, df):
    return df.loc[(df.Description.apply(lambda x: search_string(s, x))) | (df.Name.apply(lambda x: search_string(s, x)))]

In [33]:
search('co-op', runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token
33,4 player co-op on advancedkubelwagon takumi ...,07/07/2014 23:37:59 +0000,Left 4 Dead 2,07/07/2014 23:37:59 +0000,1003.0,"[Left, 4, Dead, 2]","[4, player, co-op, on, advancedkubelwagon, , t..."
53,co-op,01/05/2012 00:48:59 +0000,Portal 2,01/04/2012 23:36:00 +0000,865.0,"[Portal, 2]",[co-op]
69,Co-op. Donations for character choices.,01/05/2012 21:48:55 +0000,Tmnt Iv: Turtles In Time,01/05/2012 21:22:00 +0000,881.0,"[Tmnt, Iv:, Turtles, In, Time]","[Co-op., Donations, for, character, choices.]"
89,Co-op run,01/06/2012 11:44:15 +0000,Lawnmower Man,01/06/2012 11:11:00 +0000,901.0,"[Lawnmower, Man]","[Co-op, run]"
120,Co-op race.,01/07/2012 17:15:00 +0000,Double Dragon 2,01/07/2012 17:15:00 +0000,932.0,"[Double, Dragon, 2]","[Co-op, race.]"
133,co-op.,01/07/2012 17:15:00 +0000,Contra Iii,01/07/2012 17:15:00 +0000,945.0,"[Contra, Iii]",[co-op.]
134,co-op,01/07/2012 17:15:00 +0000,Kirby And The Amazing Mirror,01/07/2012 17:15:00 +0000,946.0,"[Kirby, And, The, Amazing, Mirror]",[co-op]
146,4-player co-op. At least; co-op is what they c...,01/07/2012 17:15:00 +0000,Magicka,01/07/2012 17:15:00 +0000,958.0,[Magicka],"[4-player, co-op., At, least;, co-op, is, what..."
221,Reaif and Tranquilite - Co-op run.,05/28/2012 09:28:00 +0000,Kirby: Return To Dreamland,05/28/2012 05:38:00 +0000,1083.0,"[Kirby:, Return, To, Dreamland]","[Reaif, , and, Tranquilite, -, Co-op, run.]"
263,4-player co-op,01/08/2013 08:07:13 +0000,Left 4 Dead,01/08/2013 06:44:00 +0000,27.0,"[Left, 4, Dead]","[4-player, co-op]"
283,co-op,01/08/2013 23:36:24 +0000,Goof Troop,01/08/2013 23:16:00 +0000,47.0,"[Goof, Troop]",[co-op]
295,4-player co-op,01/09/2013 13:36:54 +0000,Scott Pilgrim Versus The World,01/09/2013 12:39:00 +0000,58.0,"[Scott, Pilgrim, Versus, The, World]","[4-player, co-op]"
326,Co-op hard mode,01/10/2013 17:17:46 +0000,Timesplitters: Future Perfect,01/10/2013 15:58:00 +0000,84.0,"[Timesplitters:, Future, Perfect]","[Co-op, hard, mode]"
345,Co-op and donations for true ending run.,01/11/2013 14:06:27 +0000,Contra: Shattered Soldier,01/11/2013 13:32:00 +0000,101.0,"[Contra:, Shattered, Soldier]","[Co-op, and, donations, for, true, ending, run.]"
425,co-op as much as PJ and Mecha Richter can coo...,07/28/2013 17:53:06 +0000,Teenage Mutant Ninja Turtles Iii: The Manhatta...,07/28/2013 17:09:00 +0000,188.0,"[Teenage, Mutant, Ninja, Turtles, Iii:, The, M...","[co-op, , as, much, as, PJ, and, Mecha, Richte..."
514,100% co-op. Donation incentive for a warps run...,01/08/2014 00:46:00 +0000,Super Mario Bros. 3,01/07/2014 22:42:00 +0000,428.0,"[Super, Mario, Bros., 3]","[100%, co-op., Donation, incentive, for, a, wa..."
524,co-op.,01/08/2014 14:01:00 +0000,Dungeons And Dragons: Shadow Over Mystara,01/08/2014 13:25:00 +0000,438.0,"[Dungeons, And, Dragons:, Shadow, Over, Mystara]",[co-op.]
527,3-player co-op,01/08/2014 19:08:00 +0000,Secret Of Mana,01/08/2014 16:38:00 +0000,440.0,"[Secret, Of, Mana]","[3-player, co-op]"
557,co-op,01/09/2014 16:41:00 +0000,Contra,01/09/2014 16:24:00 +0000,465.0,[Contra],[co-op]
558,co-op,01/09/2014 16:59:00 +0000,Super C,01/09/2014 16:41:00 +0000,466.0,"[Super, C]",[co-op]
560,co-op,01/09/2014 17:41:00 +0000,Chip 'N Dale: Rescue Rangers,01/09/2014 17:25:00 +0000,468.0,"[Chip, 'N, Dale:, Rescue, Rangers]",[co-op]
576,co-op or solo co-op,01/10/2014 09:20:00 +0000,Portal 2,01/10/2014 08:27:00 +0000,481.0,"[Portal, 2]","[co-op, or, solo, co-op]"
579,2014's Octodad? co-op,01/10/2014 12:16:00 +0000,Surgeon Simulator 2013,01/10/2014 11:36:00 +0000,484.0,"[Surgeon, Simulator, 2013]","[2014's, Octodad?, co-op]"
580,co-op,01/10/2014 15:10:00 +0000,Borderlands 2,01/10/2014 12:16:00 +0000,485.0,"[Borderlands, 2]",[co-op]
584,co-op. Donations for a THPS3 run,01/10/2014 17:33:00 +0000,Tony Hawk's American Wasteland,01/10/2014 17:15:00 +0000,489.0,"[Tony, Hawk's, American, Wasteland]","[co-op., Donations, for, a, THPS3, run]"
596,Co-op run.,01/11/2014 08:49:00 +0000,Goldeneye,01/11/2014 08:11:00 +0000,501.0,[Goldeneye],"[Co-op, run.]"
696,Co-op run,06/25/2014 20:50:00 +0000,Battletoads & Double Dragon,06/25/2014 20:07:00 +0000,686.0,"[Battletoads, &, Double, Dragon]","[Co-op, run]"
704,Co-op run,06/26/2014 04:38:00 +0000,Risk Of Rain,06/26/2014 04:09:00 +0000,618.0,"[Risk, Of, Rain]","[Co-op, run]"
732,co-op,06/27/2014 10:59:00 +0000,Chip And Dale: Rescue Rangers 2,06/27/2014 10:29:00 +0000,645.0,"[Chip, And, Dale:, Rescue, Rangers, 2]",[co-op]
733,co-op,06/27/2014 11:45:00 +0000,Bubble Bobble,06/27/2014 10:59:00 +0000,646.0,"[Bubble, Bobble]",[co-op]
...,...,...,...,...,...,...,...
965,Bonus game #1,07/27/2015 22:28:00 +0000,Bonus! Octodad Dadliest Catch Co-Op Run,07/27/2015 21:55:00 +0000,1148.0,"[Bonus!, Octodad, Dadliest, Catch, Co-Op, Run]","[Bonus, game, #1]"
1013,Co-op incentive for Expert mode,07/29/2015 18:21:00 +0000,Gunstar Heroes,07/29/2015 17:21:00 +0000,1198.0,"[Gunstar, Heroes]","[Co-op, , incentive, for, Expert, mode]"
1091,Co-op run incentive for 100%,08/02/2015 06:33:04 +0000,Chrono Trigger,08/02/2015 01:19:00 +0000,1282.0,"[Chrono, Trigger]","[Co-op, run, , incentive, for, 100%]"
1109,NaN,01/04/2016 12:46:33 +0000,Left 4 Dead 2 Main Campaigns Co-Op,01/04/2016 11:22:33 +0000,1611.0,"[Left, 4, Dead, 2, Main, Campaigns, Co-Op]",[]
1112,Donation Incentive: Co-op with Optimus Prime,01/04/2016 16:53:08 +0000,Transformers: Devastation Any% Ng+ Prime Diffi...,01/04/2016 15:36:33 +0000,1614.0,"[Transformers:, Devastation, Any%, Ng+, Prime,...","[Donation, Incentive:, Co-op, with, Optimus, P..."
1120,Beginning of Indie Game Block.,01/05/2016 03:49:18 +0000,Battleblock Theater Any% Co-Op Insane,01/05/2016 01:38:18 +0000,1622.0,"[Battleblock, Theater, Any%, Co-Op, Insane]","[Beginning, of, Indie, Game, Block.]"
1136,Donation Incentive: Character Costume Bidwar,01/05/2016 16:34:18 +0000,Lara Croft And The Guardian Of Light Any% Ng+ ...,01/05/2016 15:54:18 +0000,1638.0,"[Lara, Croft, And, The, Guardian, Of, Light, A...","[Donation, Incentive:, Character, Costume, Bid..."
1145,Bonus Incentive: Chapter 6 DLC,01/06/2016 03:56:41 +0000,Portal 2 Co-Op,01/06/2016 02:24:41 +0000,1647.0,"[Portal, 2, Co-Op]","[Bonus, Incentive:, Chapter, 6, DLC]"
1146,NaN,01/06/2016 04:23:41 +0000,Alien Swarm Any% Co-Op Deathless,01/06/2016 03:56:41 +0000,1648.0,"[Alien, Swarm, Any%, Co-Op, Deathless]",[]
1231,Donation Incentives: Filename Bidwar Blindfol...,01/09/2016 10:07:27 +0000,The Legend Of Zelda: Majora's Mask 4p Co-Op 100%,01/09/2016 04:31:27 +0000,1732.0,"[The, Legend, Of, Zelda:, Majora's, Mask, 4p, ...","[Donation, Incentives:, Filename, Bidwar, , Bl..."
1350,NaN,07/07/2016 04:50:00 +0000,Judge Dredd: Dredd Vs. Death Co-Op Jury,07/07/2016 03:54:00 +0000,1864.0,"[Judge, Dredd:, Dredd, Vs., Death, Co-Op, Jury]",[]
1380,NaN,07/08/2016 09:03:00 +0000,Trine 3: Artifacts Of Power Classic Co-Op Any%,07/08/2016 07:52:53 +0000,1894.0,"[Trine, 3:, Artifacts, Of, Power, Classic, Co-...",[]
1394,NaN,07/08/2016 15:09:00 +0000,Kirby & The Amazing Mirror Co-Op Any%,07/08/2016 14:31:00 +0000,1908.0,"[Kirby, &, The, Amazing, Mirror, Co-Op, Any%]",[]
1429,NaN,01/08/2017 22:30:00 +0000,Borderlands 2 2 Player Co-Op,01/08/2017 20:23:00 +0000,1948.0,"[Borderlands, 2, 2, Player, Co-Op]",[]
1496,NaN,01/11/2017 08:02:56 +0000,Gauntlet Any% Co-Op,01/11/2017 07:28:56 +0000,2016.0,"[Gauntlet, Any%, Co-Op]",[]
1513,NaN,01/11/2017 15:25:00 +0000,Secrets Of Grindea Arcade Mode Co-Op,01/11/2017 14:28:00 +0000,2034.0,"[Secrets, Of, Grindea, Arcade, Mode, Co-Op]",[]
1526,NaN,01/12/2017 05:19:10 +0000,Batman Forever Any% Co-Op,01/12/2017 04:28:10 +0000,2047.0,"[Batman, Forever, Any%, Co-Op]",[]
1531,NaN,01/12/2017 07:39:09 +0000,A Nightmare On Elm Street 4-Player Co-Op,01/12/2017 07:05:10 +0000,2052.0,"[A, Nightmare, On, Elm, Street, 4-Player, Co-Op]",[]
1544,NaN,01/12/2017 15:04:59 +0000,Left 4 Dead 1 All Campaigns Co-Op,01/12/2017 13:44:59 +0000,2063.0,"[Left, 4, Dead, 1, All, Campaigns, Co-Op]",[]
1546,NaN,01/12/2017 17:54:59 +0000,Trauma Center: New Blood Co-Op Any% Normal,01/12/2017 15:58:59 +0000,2065.0,"[Trauma, Center:, New, Blood, Co-Op, Any%, Nor...",[]
1553,NaN,01/13/2017 00:29:00 +0000,Kirby's Dream Land 3 Best Ending (Co-Op),01/12/2017 22:37:59 +0000,2072.0,"[Kirby's, Dream, Land, 3, Best, Ending, (Co-Op)]",[]
1557,NaN,01/13/2017 07:13:00 +0000,Grief Syndrome Any% 1 Player Co-Op,01/13/2017 06:43:00 +0000,2076.0,"[Grief, Syndrome, Any%, 1, Player, Co-Op]",[]
1619,NaN,07/03/2017 09:13:00 +0000,Assault Android Cactus 2p Co-Op Campaign,07/03/2017 08:10:00 +0000,2142.0,"[Assault, Android, Cactus, 2p, Co-Op, Campaign]",[]
1687,NaN,07/06/2017 08:05:00 +0000,Divinity: Original Sin Any% (Co-Op),07/06/2017 07:34:00 +0000,2213.0,"[Divinity:, Original, Sin, Any%, (Co-Op)]",[]
1804,NaN,01/08/2018 07:18:00 +0000,Littlebigplanet 2 Co-Op New Game+,01/08/2018 05:32:00 +0000,2653.0,"[Littlebigplanet, 2, Co-Op, New, Game+]",[]
1846,NaN,01/10/2018 02:05:00 +0000,Left 4 Dead 2 Main Campaigns Co-Op,01/10/2018 00:53:00 +0000,2699.0,"[Left, 4, Dead, 2, Main, Campaigns, Co-Op]",[]
1847,NaN,01/10/2018 04:05:00 +0000,Dying Light Any% Co-Op,01/10/2018 02:05:00 +0000,2700.0,"[Dying, Light, Any%, Co-Op]",[]
1894,NaN,01/11/2018 17:43:00 +0000,The Legend Of The Mystical Ninja Any% 2-Player...,01/11/2018 17:03:00 +0000,2747.0,"[The, Legend, Of, The, Mystical, Ninja, Any%, ...",[]
2065,NaN,06/29/2018 11:07:00 +0000,Borderlands: The Pre-Sequel! Co-Op Any%,06/29/2018 08:32:00 +0000,3078.0,"[Borderlands:, The, Pre-Sequel!, Co-Op, Any%]",[]
2077,NaN,06/29/2018 20:51:23 +0000,Goof Troop Co-Op,06/29/2018 20:04:23 +0000,3091.0,"[Goof, Troop, Co-Op]",[]

In [34]:
search('2p1c', runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token
1143,Bonus Incentive: Super Metroid (Any% 2p1c - Oa...,01/06/2016 00:06:41 +0000,Super Metroid Bonus Any% 2p1c,01/05/2016 22:49:40 +0000,1644.0,"[Super, Metroid, Bonus, Any%, 2p1c]","[Bonus, Incentive:, Super, Metroid, (Any%, 2p1..."
1239,Bonus Incentive: Mario Kart 64 (All Cups 2p1c ...,01/09/2016 20:55:27 +0000,Mario Kart 64 All Cups 2p1c,01/09/2016 20:01:27 +0000,1740.0,"[Mario, Kart, 64, All, Cups, 2p1c]","[Bonus, Incentive:, Mario, Kart, 64, (All, Cup..."

In [35]:
search('%', runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token
5,100% racetranquilite and dessyreqt,07/07/2014 23:37:56 +0000,Super Metroid,07/07/2014 23:37:56 +0000,977.0,"[Super, Metroid]","[100%, racetranquilite, and, dessyreqt]"
43,100%,07/07/2014 23:38:00 +0000,Demon's Crest,07/07/2014 23:38:00 +0000,1013.0,"[Demon's, Crest]",[100%]
54,100%,01/05/2012 04:14:57 +0000,Super Mario World 2: Yoshi's Island,01/05/2012 01:00:00 +0000,866.0,"[Super, Mario, World, 2:, Yoshi's, Island]",[100%]
81,Race. Donations for low% or 100%.,01/06/2012 07:06:50 +0000,Mega Man X,01/06/2012 06:26:00 +0000,893.0,"[Mega, Man, X]","[Race., Donations, for, low%, or, 100%.]"
82,any%,01/06/2012 07:44:42 +0000,Mega Man X2,01/06/2012 07:09:00 +0000,894.0,"[Mega, Man, X2]",[any%]
109,100%. Donations for small mario-only.,01/07/2012 07:08:37 +0000,Super Mario Bros. 3,01/07/2012 05:38:00 +0000,921.0,"[Super, Mario, Bros., 3]","[100%., Donations, for, small, mario-only.]"
112,theseawolf1 - Added by Donation 100% Good,01/07/2012 13:29:56 +0000,Demon's Crest,01/07/2012 12:36:00 +0000,924.0,"[Demon's, Crest]","[theseawolf1, -, Added, by, Donation, , 100%, ..."
118,Julius Mode. Donations for any% or all bosses.,01/07/2012 17:31:50 +0000,Castlevania: Aria Of Sorrow,01/07/2012 17:15:00 +0000,930.0,"[Castlevania:, Aria, Of, Sorrow]","[Julius, Mode., Donations, for, any%, or, all,..."
121,100%,01/07/2012 17:15:00 +0000,Metroid Zero Mission,01/07/2012 17:15:00 +0000,933.0,"[Metroid, Zero, Mission]",[100%]
122,any%,01/07/2012 17:15:00 +0000,Super Metroid,01/07/2012 17:15:00 +0000,934.0,"[Super, Metroid]",[any%]
152,Donations for character choice. Possibly low%.,01/07/2012 17:15:00 +0000,Sunset Riders,01/07/2012 17:15:00 +0000,964.0,"[Sunset, Riders]","[Donations, for, character, choice., Possibly,..."
163,UltraJman - 100%,05/25/2012 02:45:14 +0000,Kirby's Dream Land 3,05/25/2012 00:58:00 +0000,1025.0,"[Kirby's, Dream, Land, 3]","[UltraJman, -, 100%]"
192,puwexil - 100%,05/26/2012 17:16:46 +0000,Illusion Of Gaia,05/26/2012 14:49:00 +0000,1054.0,"[Illusion, Of, Gaia]","[puwexil, -, 100%]"
207,Dragondarch - 1% run. Donations for the secret...,05/27/2012 06:33:00 +0000,Metroid Fusion,05/27/2012 04:18:00 +0000,1069.0,"[Metroid, Fusion]","[Dragondarch, -, 1%, run., Donations, for, the..."
214,PEACHES_ - 100%,05/27/2012 23:23:00 +0000,Blast Corps,05/27/2012 21:18:00 +0000,1076.0,"[Blast, Corps]","[PEACHES_, -, 100%]"
222,Essentia - Donations for 100%. Return of the S...,05/28/2012 13:13:00 +0000,Final Fantasy Vi,05/28/2012 06:13:00 +0000,1084.0,"[Final, Fantasy, Vi]","[Essentia, -, Donations, for, 100%., Return, o..."
236,100%. Donations for an any% run,01/06/2013 21:54:14 +0000,Shadow Complex,01/06/2013 20:48:00 +0000,3.0,"[Shadow, Complex]","[100%., Donations, for, an, any%, run]"
237,Any%,01/06/2013 23:20:01 +0000,Mischief Makers,01/06/2013 22:19:00 +0000,4.0,"[Mischief, Makers]",[Any%]
238,Metaknightmare mode 100% race.,01/07/2013 00:06:05 +0000,Kirby: Nightmare In Dream Land,01/06/2013 23:30:00 +0000,5.0,"[Kirby:, Nightmare, In, Dream, Land]","[Metaknightmare, mode, 100%, race.]"
239,any% donations for 100%,01/07/2013 02:55:54 +0000,Super Mario World 2: Yoshi's Island,01/07/2013 00:07:00 +0000,6.0,"[Super, Mario, World, 2:, Yoshi's, Island]","[any%, , donations, for, 100%]"
240,any% glitched,01/07/2013 04:07:31 +0000,Donkey Kong 64,01/07/2013 03:12:00 +0000,7.0,"[Donkey, Kong, 64]","[any%, glitched]"
241,100%,01/07/2013 06:51:56 +0000,Banjo-Kazooie,01/07/2013 04:17:00 +0000,8.0,[Banjo-Kazooie],[100%]
257,No whistles. Donations for 100%,01/07/2013 23:40:48 +0000,Super Mario Bros. 3,01/07/2013 22:20:00 +0000,22.0,"[Super, Mario, Bros., 3]","[No, whistles., Donations, for, 100%]"
260,XBLA version 106% donations for the expert re...,01/08/2013 03:49:36 +0000,Super Meat Boy,01/08/2013 02:02:00 +0000,24.0,"[Super, Meat, Boy]","[XBLA, version, 106%, , donations, for, the, e..."
280,Any%,01/08/2013 22:29:51 +0000,Ninja Gaiden (Nes),01/08/2013 22:12:00 +0000,43.0,"[Ninja, Gaiden, (Nes)]",[Any%]
282,Donations for low% (no-pickup run),01/08/2013 23:13:06 +0000,Ninja Gaiden 3,01/08/2013 22:55:00 +0000,45.0,"[Ninja, Gaiden, 3]","[Donations, for, low%, (no-pickup, run)]"
290,100%,01/09/2013 06:24:40 +0000,Metroid Prime,01/09/2013 04:35:00 +0000,53.0,"[Metroid, Prime]",[100%]
291,Any%,01/09/2013 08:05:59 +0000,Metroid Prime 2,01/09/2013 06:33:00 +0000,54.0,"[Metroid, Prime, 2]",[Any%]
302,Any%,01/10/2013 01:03:55 +0000,Donkey Kong Country Returns,01/09/2013 23:20:00 +0000,64.0,"[Donkey, Kong, Country, Returns]",[Any%]
331,Donations for any% or 100%,01/10/2013 23:24:03 +0000,Vvvvvv,01/10/2013 23:04:00 +0000,88.0,[Vvvvvv],"[Donations, for, any%, or, 100%]"
...,...,...,...,...,...,...,...
2051,NaN,06/28/2018 16:23:00 +0000,The Legend Of Zelda Low% Race,06/28/2018 14:56:00 +0000,3064.0,"[The, Legend, Of, Zelda, Low%, Race]",[]
2052,NaN,06/28/2018 18:36:00 +0000,The Legend Of Zelda: Oracle Of Seasons Any%,06/28/2018 16:23:00 +0000,3065.0,"[The, Legend, Of, Zelda:, Oracle, Of, Seasons,...",[]
2053,NaN,06/28/2018 21:14:00 +0000,Paper Mario Any%,06/28/2018 18:36:00 +0000,3066.0,"[Paper, Mario, Any%]",[]
2055,NaN,06/28/2018 22:37:00 +0000,Deus Ex Any%,06/28/2018 21:47:00 +0000,3068.0,"[Deus, Ex, Any%]",[]
2056,NaN,06/28/2018 23:59:00 +0000,Deus Ex Mankind Divided Any%,06/28/2018 22:37:00 +0000,3069.0,"[Deus, Ex, Mankind, Divided, Any%]",[]
2062,Bonus Incentive run by ProtoAus,06/29/2018 07:26:00 +0000,Half-Life Any%,06/29/2018 06:38:00 +0000,3071.0,"[Half-Life, Any%]","[Bonus, Incentive, run, by, ProtoAus]"
2065,NaN,06/29/2018 11:07:00 +0000,Borderlands: The Pre-Sequel! Co-Op Any%,06/29/2018 08:32:00 +0000,3078.0,"[Borderlands:, The, Pre-Sequel!, Co-Op, Any%]",[]
2066,NaN,06/29/2018 12:31:00 +0000,Bionic Commando Any%,06/29/2018 11:07:00 +0000,3079.0,"[Bionic, Commando, Any%]",[]
2067,NaN,06/29/2018 13:14:00 +0000,Bound Any%,06/29/2018 12:31:00 +0000,3080.0,"[Bound, Any%]",[]
2069,NaN,06/29/2018 14:15:00 +0000,Double Dragon Any%,06/29/2018 13:53:00 +0000,3082.0,"[Double, Dragon, Any%]",[]
2070,NaN,06/29/2018 14:37:00 +0000,Double Dragon Ii: The Revenge Any%,06/29/2018 14:15:00 +0000,3083.0,"[Double, Dragon, Ii:, The, Revenge, Any%]",[]
2072,NaN,06/29/2018 15:59:14 +0000,Streets Of Rage 2 Mania%,06/29/2018 14:54:00 +0000,3085.0,"[Streets, Of, Rage, 2, Mania%]",[]
2073,NaN,06/29/2018 16:43:25 +0000,Rockman No-Constancy Any% Normal,06/29/2018 15:59:14 +0000,3087.0,"[Rockman, No-Constancy, Any%, Normal]",[]
2074,NaN,06/29/2018 17:40:47 +0000,Mega Man 7 Any%,06/29/2018 16:43:25 +0000,3088.0,"[Mega, Man, 7, Any%]",[]
2075,NaN,06/29/2018 18:44:31 +0000,Mega Man 8 Any% Race,06/29/2018 17:40:47 +0000,3089.0,"[Mega, Man, 8, Any%, Race]",[]
2076,NaN,06/29/2018 20:04:23 +0000,Bionic Commando Rearmed 2 Any%,06/29/2018 18:44:31 +0000,3118.0,"[Bionic, Commando, Rearmed, 2, Any%]",[]
2078,NaN,06/30/2018 00:19:23 +0000,Kingdom Hearts Hd 1.5 Remix (Kh1fm) Any% (Leve...,06/29/2018 20:51:23 +0000,3092.0,"[Kingdom, Hearts, Hd, 1.5, Remix, (Kh1fm), Any...",[]
2080,NaN,06/30/2018 03:32:33 +0000,The Legend Of Zelda: The Wind Waker Hd Any%,06/30/2018 01:33:13 +0000,3094.0,"[The, Legend, Of, Zelda:, The, Wind, Waker, Hd...",[]
2081,NaN,06/30/2018 04:20:00 +0000,Tasbot Plays Celeste Any% Tas By Devilsquirrel...,06/30/2018 03:32:33 +0000,3095.0,"[Tasbot, Plays, Celeste, Any%, Tas, By, Devils...",[]
2082,NaN,06/30/2018 04:36:00 +0000,Tasbot Plays Super Metroid 0% By Sniq And Tota...,06/30/2018 04:20:00 +0000,3097.0,"[Tasbot, Plays, Super, Metroid, 0%, By, Sniq, ...",[]
2083,NaN,06/30/2018 05:09:00 +0000,Tasbot Plays F-Zero Gx By Talented Authors Tas...,06/30/2018 04:36:00 +0000,3096.0,"[Tasbot, Plays, F-Zero, Gx, By, Talented, Auth...",[]
2084,NaN,06/30/2018 08:31:00 +0000,Pokemon Yellow/Red Any% Glitchless 2 Games 1 C...,06/30/2018 05:09:00 +0000,3100.0,"[Pokemon, Yellow/Red, Any%, Glitchless, 2, Gam...",[]
2085,NaN,06/30/2018 09:03:00 +0000,Star Wars Jedi Knight: Dark Forces Ii Any%,06/30/2018 08:31:00 +0000,3101.0,"[Star, Wars, Jedi, Knight:, Dark, Forces, Ii, ...",[]
2086,NaN,06/30/2018 09:33:00 +0000,Star Wars Jedi Knight: Mysteries Of The Sith Any%,06/30/2018 09:03:00 +0000,3102.0,"[Star, Wars, Jedi, Knight:, Mysteries, Of, The...",[]
2087,NaN,06/30/2018 10:31:00 +0000,Super Star Wars: The Empire Strikes Back Any%,06/30/2018 09:33:00 +0000,3103.0,"[Super, Star, Wars:, The, Empire, Strikes, Bac...",[]
2088,NaN,06/30/2018 11:40:00 +0000,Hob Any% No Clip (One-Handed),06/30/2018 10:31:00 +0000,3104.0,"[Hob, Any%, No, Clip, (One-Handed)]",[]
2092,NaN,06/30/2018 14:42:00 +0000,Crash Bandicoot: N. Sane Trilogy Crash Bandico...,06/30/2018 13:37:00 +0000,3108.0,"[Crash, Bandicoot:, N., Sane, Trilogy, Crash, ...",[]
2094,NaN,06/30/2018 16:08:54 +0000,Kirby's Adventure 100% No Major Glitches,06/30/2018 15:05:00 +0000,3110.0,"[Kirby's, Adventure, 100%, No, Major, Glitches]",[]
2099,NaN,07/01/2018 00:20:54 +0000,Super Mario Odyssey Any%,06/30/2018 22:52:54 +0000,3115.0,"[Super, Mario, Odyssey, Any%]",[]
2100,NaN,07/01/2018 07:30:54 +0000,Final Fantasy Vi Glitchless 100% (All Characte...,07/01/2018 00:20:54 +0000,3116.0,"[Final, Fantasy, Vi, Glitchless, 100%, (All, C...",[]

check:
- all (all stages)
- no (no major glitches)
- new/ng (ng+)
- difficulty levels (easy/normal/hard + exceptions: insane, legendary, etc)

extraction: split after one of these words until end/./(others)

In [127]:
# regex for common category names
regex = [r'\w+ ?%', r'\d+[ -](stars?|exits?|shines?)', '(^| )TAS(bot)?', r'\w+less', r'(^| )all [\w &]+',
         r'no [\w ]+', r'[\w -]+only', r'\w+ Mode', r'(true |dark )?\w* ?(?<!automata )ending( A)?', 'beat the game',
         'oob', '(in|out)[- ]?(of)?[- ]?bounds', r'(individual|bonus|secret|extra|master)?(?<!lost)( levels?| stages?)( \d)?( \w*)?',
         r'(community/ninja/retro)?\d*[- ]tracks?(?!er)( showcase)?', '(reverse boss order|RBO|reverse badge acquisition)', 'deathwarps',
         r'\dp\dc', r'\d (game|player)s? \d controllers?', 
         r'new game ?\+?', r'ng\+', 'blind(fold(ed)?)?', r'(\d|multi|single)[ -]?player', '(solo |^| )co-?op',
         '(relay)?(^| )race', '(1|one)[ -]?handed', 'bingo', r'\d+[- ](boss|meters|talisman|pups|cubes|loops|trinkets|egg|bags of ca\$h)',
         r'easy(\w| )*', r'normal(\w| )*', r'hard(est|core)?(\w| )*', r'insane(\w| )*', 
         r'beginner(\w| )*', r'advanced(\w| )*', r'expert(\w| )*',
         'legendary', 'tourist', 'not impossible', 'casual', 'brutal', 
         '(00 |perfect )?agent', '(european )?extreme', 'watch me die', 
         'heavy', 'ultra-violence', 'UV ', 'be gentle', r'\w* ?difficulty', 'pacifist', r'glitch(ed)?(\w| )+']

In [37]:
def try_search(exp, x):
    try:
        return exp.search(x).group()
    except:
        return np.nan

def find_cat(s):
    exp = re.compile(s, re.IGNORECASE)
    return runs.Description.apply(lambda x: try_search(exp, x)), runs.Name.apply(lambda x: try_search(exp, x))

In [38]:
runs.Description.str.findall(r'\d+[- ][a-zA-Z]+').str.join(' ').str.cat(sep = ' ')

'  8 way 70 star    4 player            4 boss              8-boss             360 version                          70-star 61-star    4-player       2 and          2 on                                              120 star           2 games                         96-exit     4-player            1 race       4-player                               00 Agent            120 star                    5 or             1 run                70 star 16-star      4-boss                             2 it        16 bags                3-player                                               3 run  2000 meters             16-star                         1 Player 2 Controllers            64 block 14 Talisman        1 player 2 controllers            00 Agent                    96 Exit 97 Exit  16 star 70 or 120 stars  1 and            16 Tracks                         4-way     4-way 4-way                 4-way                       4-way                          2 loop 2 loop                      30 any 3 and                2 players 1 controller                        1 through    151 Pokemon      2 players 1 controller  120 star       1 Race 64 Multiplayer 16 Star   3 and    1 Proud             6 DLC              2-way 32 Characters                2 Turtle   763907 and             64 TAS    3 slots    9 Any   70 Race  '

In [39]:
runs.Name.str.findall(r'\d+[- ][a-zA-Z]+').str.join(' ').str.cat(sep = ' ')

'                               4 Dead     94 Or                                                                                                                      3 Katamari                                                                       1 Or                                    4 Dead          7 Vs                                                                                                                   5 Or 6 Bid                                                                                                        1 Vs 2 Bid                   6 Golden                                                                                                                                                        8 Eyes                                                                                1 Vs 2 Bid      3 Way                                        2 Battle                                                                   3 And                                           2 Episode                   1 And 2 Bid                      3 Lost                              1 Handed                       3 Low                                                     3 Burst                                          64 Any              120 Star 64 Multiplayer 16 Star    2 Any  4 Dead 2 Main   1-Handed       5 Remix          15 Scroll               2 Any 2 Co           2 Classic  2 Crazy  3 All             3 Any   0 Exit 96 Exit                               4 Legendary    64 Any           4 Bcas 10 Any 9 Any 6 Any 2 Any  2 Any     3 Any    32 Tracks 64 All 64 Star 4-Way       64 Floor         1 Player 2 Controllers  2 Any   1080 Avalanche                 8 Any 3 Any 5 Any 9 Any                   64 Any           2 Any   1-Handed        3 Any 2 Leon   64 Any 64 Any  64 Ds 50 Star       3 Any 2 Any  2 Any              2 Any     16 Bags       2 Any         3 Any 4 Any         1 Any                 2 Any  2 Low               2 Memory 20 Trinkets 3 One    70 Star 70 Star  2 Any  2 Player                     2 Any           2 Story         4 Any   6-Episode 2 Any  3 Any          2 Any                    2 Any  0 Kunai            6 Any   9 Any 2 Legendary       4-Player             4 Dead 1 All    2 Sonic     3 Best   2 Any 1 Player              3 Any   4 Any                    2 Any  2 Players 1 Controller  2 By  1 By   3 Any     1-Handed  2 Any            2 Any      100 Egg    2011 Tails     64 No         2 All 4 Any          2 Any  2 Any 2 Any       3 Any        1001 Spikes    2 Best  6 All  2 Any 3 Any        2 Single                8-Way 2-Players 1-Controller             4 Any      1 Data        2 Any     120 Star   2 Solo    4 Zero 3 Ng     2 Any     6 Any        2 Any    2 Tas         2 Bid  4 Normal              2 Any        2 Co               3 Best   3 Any 4 X                       4 Dead 2 Main  7 Biohazard                2-Player        4 Normal   120 Shines 64 Any  5-Year                2-Player  2 Ng                            2 Any 3 Team 2 Games 1 Controller    2 Any 6 Golden    3-Way   1 Sorcerer  3 Any                4 New    2 Loops        2 Player        3 Any  5-Stage  1 Character   6 Any 9 Any 4 Any 2 Buster       10 Pups 25 Cubes    4 Boss        2 Sonic 3 And    2 Legendary   2 Any   2 Story                      2 Laps  2 Any                  3 All  8 Deluxe 32 Tracks       1 Player 2 Controllers    2 Mania  7 Any 8 Any 2 Any  5 Remix 1 Proud 70 Star     2 Games 1 Controller       14 Talisman 1 Any   2 Warpless  3 Blind    '

In [40]:
def extract_categories(runs, regex):
    regex_cols = [exp + s for exp in regex for s in ['_desc', '_name']]
    
    for exp in regex:
        runs[exp + '_desc'], runs[exp + '_name'] = find_cat(exp)
    
    return runs

def concat_category(row, regex_cols):
    s = ''
    for col in regex_cols:
        try:
            if row[col].strip() not in s.strip():
                s += row[col] + ' '
        except:
            pass
    
    return s

In [128]:
new_runs = extract_categories(runs.copy(), regex)

In [129]:
regex_cols = [exp + s for exp in regex for s in ['_desc', '_name']]

In [130]:
new_runs['category'] = new_runs.apply(lambda x: concat_category(x, regex_cols), axis = 1)

In [44]:
# strips categories from game names by truncating the name after any word in the category appears
def strip_categories(row):
    # if there is no category, don't change the name
    if len(row.category) == 0:
        return row.Name
    else:
        # list of indices for the category words actually in the name
        indices = [row.Name.find(s) for s in row.category.split(' ') if len(s) > 0 and s in row.Name]
        
        if len(indices) == 0 or min(indices) == -1:
            return row.Name
        else:
            return row.Name[:min(indices)]

In [131]:
new_runs['new_Name'] = new_runs.apply(strip_categories, axis = 1)

In [132]:
new_runs = new_runs.drop(regex_cols, axis = 1)

In [133]:
new_runs.loc[new_runs.category.apply(lambda x: len(x) > 0)].shape

(1435, 9)

In [48]:
new_runs.head()

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
0,NaN,07/07/2014 23:37:56 +0000,Toejam And Earl 2: Panic On Funkotron,07/07/2014 23:37:56 +0000,972.0,"[Toejam, And, Earl, 2:, Panic, On, Funkotron]",[],,Toejam And Earl 2: Panic On Funkotron
1,NaN,07/07/2014 23:37:56 +0000,Mega Man 3,07/07/2014 23:37:56 +0000,973.0,"[Mega, Man, 3]",[],,Mega Man 3
2,NaN,07/07/2014 23:37:56 +0000,Limbo,07/07/2014 23:37:56 +0000,974.0,[Limbo],[],,Limbo
3,NaN,07/07/2014 23:37:56 +0000,Rayman 2: The Great Escape,07/07/2014 23:37:56 +0000,975.0,"[Rayman, 2:, The, Great, Escape]",[],,Rayman 2: The Great Escape
4,NaN,07/07/2014 23:37:56 +0000,Quake 2,07/07/2014 23:37:56 +0000,976.0,"[Quake, 2]",[],,Quake 2

In [137]:
new_runs.loc[new_runs.category.apply(lambda x: len(x) == 0)].sample(10)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
571,Scenario bid war,01/10/2014 01:09:00 +0000,Age Of Empires 2,01/10/2014 00:49:00 +0000,476.0,"[Age, Of, Empires, 2]","[Scenario, bid, war]",,Age Of Empires 2
910,bid war between games?,01/09/2015 17:59:00 +0000,Pokemon Red/Blue,01/09/2015 17:27:00 +0000,846.0,"[Pokemon, Red/Blue]","[bid, war, between, games?]",,Pokemon Red/Blue
474,WTFJapan,01/06/2014 13:51:00 +0000,Yume Penguin Monogatari,01/06/2014 13:31:00 +0000,392.0,"[Yume, Penguin, Monogatari]",[WTFJapan],,Yume Penguin Monogatari
28,NaN,07/07/2014 23:37:58 +0000,Snake Rattle N Roll,07/07/2014 23:37:58 +0000,998.0,"[Snake, Rattle, N, Roll]",[],,Snake Rattle N Roll
234,NaN,01/06/2013 19:08:45 +0000,Ape Escape,01/06/2013 18:15:00 +0000,1.0,"[Ape, Escape]",[],,Ape Escape
400,Dawn vs. Portrait vs. Order,07/27/2013 13:29:00 +0000,Castlevania: Order Of Ecclesia,07/27/2013 12:04:00 +0000,167.0,"[Castlevania:, Order, Of, Ecclesia]","[Dawn, vs., Portrait, vs., Order]",,Castlevania: Order Of Ecclesia
228,Darkkobold,05/28/2012 13:48:00 +0000,Duck Tales,05/28/2012 13:33:00 +0000,1090.0,"[Duck, Tales]",[Darkkobold],,Duck Tales
42,NaN,07/07/2014 23:38:00 +0000,Legend Of Zelda: A Link To The Past,07/07/2014 23:38:00 +0000,1012.0,"[Legend, Of, Zelda:, A, Link, To, The, Past]",[],,Legend Of Zelda: A Link To The Past
165,mikwuyma,05/25/2012 03:59:34 +0000,Metal Slug 3,05/25/2012 03:28:00 +0000,1027.0,"[Metal, Slug, 3]",[mikwuyma],,Metal Slug 3
1871,NaN,01/10/2018 21:04:00 +0000,Strider Live Tutorial Showcase,01/10/2018 20:08:00 +0000,2722.0,"[Strider, Live, Tutorial, Showcase]",[],,Strider Live Tutorial Showcase

In [65]:
search('stage', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
156,Donations for which song is played in the long...,01/07/2012 17:15:00 +0000,We <3 Katamari,01/07/2012 17:15:00 +0000,968.0,"[We, <3, Katamari]","[Donations, for, which, song, is, played, in, ...",stage,We <3 Katamari
195,Duckfist - Donations for the special stages.,05/26/2012 20:08:00 +0000,Mega Man 10,05/26/2012 19:23:00 +0000,1057.0,"[Mega, Man, 10]","[Duckfist, -, Donations, for, the, special, st...",stages,Mega Man 10
382,It's single-player so Celise can't upstage him.,07/26/2013 21:05:00 +0000,Sonic The Hedgehog,07/26/2013 20:37:00 +0000,151.0,"[Sonic, The, Hedgehog]","[It's, single-player, so, Celise, can't, upsta...",single-player,Sonic The Hedgehog
612,All Stages,06/23/2014 00:03:00 +0000,Donkey Kong Country,06/22/2014 23:20:00 +0000,530.0,"[Donkey, Kong, Country]","[All, Stages]",All Stages,Donkey Kong Country
638,Incentive for Eggmanland; end of Sonic block,06/23/2014 22:47:00 +0000,Sonic Unleashed (Day Stages Only),06/23/2014 21:34:00 +0000,552.0,"[Sonic, Unleashed, (Day, Stages, Only)]","[Incentive, for, Eggmanland;, end, of, Sonic, ...",Day Stages Only,Sonic Unleashed (
937,All Stages race!,07/26/2015 22:52:00 +0000,Donkey Kong Country,07/26/2015 22:10:00 +0000,1120.0,"[Donkey, Kong, Country]","[All, Stages, race!]",All Stages race,Donkey Kong Country
986,Incentive for All Stages race,07/28/2015 15:24:00 +0000,Wizards & Warriors,07/28/2015 14:56:00 +0000,1168.0,"[Wizards, &, Warriors]","[Incentive, for, All, Stages, , race]",All Stages race,Wizards & Warriors
1107,Bonus Incentive: All Stages,01/04/2016 10:47:33 +0000,Strider 2 Any%,01/04/2016 10:10:33 +0000,1609.0,"[Strider, 2, Any%]","[Bonus, Incentive:, All, Stages]",Any% All Stages,Strider 2
1160,NaN,01/06/2016 14:08:41 +0000,Sonic Advance 3 All Stages,01/06/2016 13:07:41 +0000,1662.0,"[Sonic, Advance, 3, All, Stages]",[],All Stages,Sonic Advance 3
1171,NaN,01/06/2016 22:07:20 +0000,Donkey Kong Country Any% All Stages,01/06/2016 21:20:10 +0000,1673.0,"[Donkey, Kong, Country, Any%, All, Stages]",[],Any% All Stages,Donkey Kong Country
1207,End of Mega Man X Block.,01/08/2016 02:40:27 +0000,Azure Striker Gunvolt Any% Speedrun Mode/All S...,01/08/2016 01:20:27 +0000,1709.0,"[Azure, Striker, Gunvolt, Any%, Speedrun, Mode...","[End, of, Mega, Man, X, Block.]",Any% Speedrun Mode Stages,Azure Striker Gunvolt
1283,NaN,07/04/2016 19:20:00 +0000,Mighty Gunvolt All Stages (Beck),07/04/2016 18:55:00 +0000,1798.0,"[Mighty, Gunvolt, All, Stages, (Beck)]",[],All Stages,Mighty Gunvolt
1432,NaN,01/09/2017 01:46:00 +0000,Mega Man All Stages,01/09/2017 01:00:00 +0000,1951.0,"[Mega, Man, All, Stages]",[],All Stages,Mega Man
1442,NaN,01/09/2017 12:25:00 +0000,Hyper Princess Pitch Combat Lady All Stages,01/09/2017 12:04:00 +0000,1961.0,"[Hyper, Princess, Pitch, Combat, Lady, , All, ...",[],All Stages,Hyper Princess Pitch Combat Lady
1503,NaN,01/11/2017 10:52:00 +0000,Little Samson All Stages Normal,01/11/2017 10:24:00 +0000,2023.0,"[Little, Samson, All, Stages, Normal]",[],All Stages Normal,Little Samson
1681,NaN,07/05/2017 23:55:00 +0000,Mega Man X6 All Stages (Normal),07/05/2017 22:52:00 +0000,2207.0,"[Mega, Man, X6, All, Stages, (Normal)]",[],All Stages Normal,Mega Man X6
1757,NaN,09/02/2017 11:13:54 +0000,Densha De D: Lightning Stage Any% Race,09/02/2017 10:33:54 +0000,2602.0,"[Densha, De, D:, Lightning, Stage, Any%, Race]",[],Any% Race Stage Any,Densha De D: Lightning
1916,NaN,01/12/2018 11:36:00 +0000,Densha De D: Lightning Stage Any%,01/12/2018 10:59:00 +0000,2770.0,"[Densha, De, D:, Lightning, Stage, Any%]",[],Any% Stage Any,Densha De D: Lightning
1921,NaN,01/12/2018 17:53:13 +0000,Super Monkey Ball Beginner Advanced Expert S...,01/12/2018 17:14:51 +0000,2775.0,"[Super, Monkey, Ball, Beginner, , Advanced, , ...",[],Beginner Advanced Expert Stages,Super Monkey Ball
1978,NaN,06/25/2018 20:27:00 +0000,Monolith 5-Stage Normal Intense Lethality,06/25/2018 20:04:00 +0000,2990.0,"[Monolith, 5-Stage, , Normal, , Intense, Letha...",[],Normal Intense Lethality,Monolith 5-Stage
2022,NaN,06/27/2018 19:13:00 +0000,Contra: Shattered Soldier Any% All Stages Race,06/27/2018 18:20:00 +0000,3033.0,"[Contra:, Shattered, Soldier, Any%, All, Stage...",[],Any% All Stages Race,Contra: Shattered Soldier

In [66]:
search('level', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
47,soma all levels ng+,07/07/2014 23:38:00 +0000,Castlevania: Harmony Of Despair,07/07/2014 23:38:00 +0000,1017.0,"[Castlevania:, Harmony, Of, Despair]","[soma, all, levels, ng+]",all levels ng ng+,Castlevania: Harmony Of Despair
101,Donations for the secret levels,01/06/2012 20:41:09 +0000,Quake,01/06/2012 20:22:00 +0000,913.0,[Quake],"[Donations, for, the, secret, levels]",secret levels,Quake
106,Dark world ending. Donations for other levels.,01/07/2012 04:37:16 +0000,Super Meat Boy,01/07/2012 03:16:00 +0000,918.0,"[Super, Meat, Boy]","[Dark, world, ending., Donations, for, other, ...",Dark world ending levels,Super Meat Boy
108,bidding war for the two,01/07/2012 05:35:02 +0000,Super Mario World/Lost Levels,01/07/2012 05:22:00 +0000,920.0,"[Super, Mario, World/Lost, Levels]","[bidding, war, for, the, two]",,Super Mario World/Lost Levels
142,Time is to account for master levels,01/07/2012 17:15:00 +0000,Super Monkey Ball,01/07/2012 17:15:00 +0000,954.0,"[Super, Monkey, Ball]","[Time, is, to, account, for, master, levels]",master levels,Super Monkey Ball
186,Tranquilite - Donations for Trinkets and extra...,05/26/2012 05:40:33 +0000,Vvvvvv,05/26/2012 05:00:25 +0000,1048.0,[Vvvvvv],"[Tranquilite, -, Donations, for, Trinkets, and...",extra levels,Vvvvvv
231,deathfire123 - Individual levels,05/28/2012 16:43:00 +0000,Katamari Forever,05/28/2012 14:33:00 +0000,1093.0,"[Katamari, Forever]","[deathfire123, -, Individual, levels]",Individual levels,Katamari Forever
260,XBLA version 106% donations for the expert re...,01/08/2013 03:49:36 +0000,Super Meat Boy,01/08/2013 02:02:00 +0000,24.0,"[Super, Meat, Boy]","[XBLA, version, 106%, , donations, for, the, e...",106% expert remix levels,Super Meat Boy
300,all levels race,01/09/2013 22:21:38 +0000,Donkey Kong Country,01/09/2013 21:41:00 +0000,62.0,"[Donkey, Kong, Country]","[all, levels, race]",all levels race,Donkey Kong Country
370,"ng+. donations for DLC level ""blind""",07/26/2013 04:30:00 +0000,Hotline Miami,07/26/2013 03:57:00 +0000,139.0,"[Hotline, Miami]","[ng+., donations, for, DLC, level, , ""blind""]",ng+ blind level,Hotline Miami
409,Richter any% by Mecha Pacifist/level 1 run by...,07/27/2013 21:06:00 +0000,Castlevania: Symphony Of The Night,07/27/2013 19:31:00 +0000,222.0,"[Castlevania:, Symphony, Of, The, Night]","[Richter, any%, by, Mecha, , Pacifist/level, 1...",any% Pacifist,Castlevania: Symphony Of The Night
439,All levels,07/29/2013 14:33:00 +0000,Dustforce,07/29/2013 12:40:00 +0000,199.0,[Dustforce],"[All, levels]",All levels,Dustforce
454,any%. Donations for Stormy Ascent bonus level,01/05/2014 19:48:00 +0000,Crash Bandicoot,01/05/2014 18:35:00 +0000,371.0,"[Crash, Bandicoot]","[any%., Donations, for, Stormy, Ascent, bonus,...",any% bonus level,Crash Bandicoot
512,NaN,01/07/2014 22:15:00 +0000,Super Mario Bros.: The Lost Levels,01/07/2014 21:24:00 +0000,426.0,"[Super, Mario, Bros.:, The, Lost, Levels]",[],,Super Mario Bros.: The Lost Levels
533,possible race and donation incentive for lost...,01/09/2014 00:52:00 +0000,Donkey Kong Country 2,01/08/2014 23:57:00 +0000,444.0,"[Donkey, Kong, Country, 2]","[possible, race, , and, donation, incentive, f...",race levels done,Donkey Kong Country 2
630,All Levels,06/23/2014 16:38:00 +0000,Aladdin (Genesis),06/23/2014 16:15:00 +0000,545.0,"[Aladdin, (Genesis)]","[All, Levels]",All Levels,Aladdin (Genesis)
709,Story mode incentive for hardcore levels,06/26/2014 07:58:00 +0000,Nitronic Rush,06/26/2014 07:13:00 +0000,630.0,"[Nitronic, Rush]","[Story, mode, , incentive, for, hardcore, levels]",Story mode hardcore levels,Nitronic Rush
837,NaN,01/07/2015 02:29:00 +0000,Super Mario Bros.: The Lost Levels,01/07/2015 01:56:00 +0000,776.0,"[Super, Mario, Bros.:, The, Lost, Levels]",[],,Super Mario Bros.: The Lost Levels
922,Agent run. Donations for all levels,01/10/2015 18:30:00 +0000,Perfect Dark,01/10/2015 17:45:00 +0000,856.0,"[Perfect, Dark]","[Agent, run., Donations, for, all, levels]",all levels Agent,Perfect Dark
1003,All Story Levels,07/29/2015 09:50:00 +0000,Bastion,07/29/2015 08:48:00 +0000,1185.0,[Bastion],"[All, Story, Levels]",All Story Levels,Bastion
1005,Critical Difficulty Level 1,07/29/2015 12:12:00 +0000,Kingdom Hearts Birth By Sleep Fm Hd,07/29/2015 10:51:00 +0000,1187.0,"[Kingdom, Hearts, Birth, By, Sleep, Fm, Hd]","[Critical, Difficulty, , Level, 1]",Critical Difficulty Level 1,Kingdom Hearts Birth By Sleep Fm Hd
1056,No Levels Early,07/31/2015 08:20:00 +0000,Donkey Kong 64,07/31/2015 05:51:00 +0000,1267.0,"[Donkey, Kong, 64]","[No, Levels, Early]",No Levels Early,Donkey Kong 64
1071,Warpless Luigi Worlds 1 through D,07/31/2015 22:24:00 +0000,Super Mario Bros: The Lost Levels,07/31/2015 21:29:00 +0000,1259.0,"[Super, Mario, Bros:, The, Lost, Levels]","[Warpless, Luigi, , Worlds, 1, through, D]",Warpless,Super Mario Bros: The Lost Levels
1097,Donation Incentive: Music Level Showcase (0:05),01/03/2016 21:35:00 +0000,Rayman Legends Any%,01/03/2016 19:37:00 +0000,1599.0,"[Rayman, Legends, Any%]","[Donation, Incentive:, Music, Level, Showcase,...",Any% Level Showcase,Rayman Legends
1119,End of Disney Block. Donation Incentives: Seph...,01/05/2016 01:38:18 +0000,Kingdom Hearts Hd 1.5 Remix Any% Proud,01/04/2016 21:53:18 +0000,1621.0,"[Kingdom, Hearts, Hd, 1.5, Remix, Any%, Proud]","[End, of, Disney, Block., Donation, Incentives...",Any% Proud Mode Level 1 Proud,Kingdom Hearts Hd
1126,NaN,01/05/2016 10:08:18 +0000,Hotline Miami Ng+ All Levels,01/05/2016 09:05:18 +0000,1628.0,"[Hotline, Miami, Ng+, All, Levels]",[],All Levels Ng+,Hotline Miami
1175,Bonus Incentive: Hard Level 2-way race. Donati...,01/07/2016 03:19:46 +0000,Super Mario Maker Custom Level Blind Race,01/07/2016 01:16:29 +0000,1677.0,"[Super, Mario, Maker, Custom, Level, Blind, Race]","[Bonus, Incentive:, Hard, Level, 2-way, race.,...",Blind race Race Hard Level 2 Level Blind,Super Mario Maker Custom
1217,Donation Incentives: Character name Bidwar Se...,01/08/2016 18:03:27 +0000,Diablo Ii: Lord Of Destruction D2:Lod Sorceres...,01/08/2016 15:58:27 +0000,1719.0,"[Diablo, Ii:, Lord, Of, Destruction, D2:Lod, S...","[Donation, Incentives:, Character, name, Bidwa...",Any% Normal Level,Diablo Ii: Lord Of Destruction D2:Lod Sorceress
1254,NaN,07/03/2016 22:46:00 +0000,Mighty Switch Force! Hyperdrive Edition Ng+ Al...,07/03/2016 21:55:00 +0000,1768.0,"[Mighty, Switch, Force!, Hyperdrive, Edition, ...",[],All Hyper Levels Ng+,Mighty Switch Force!
1308,NaN,07/05/2016 23:10:24 +0000,Dustforce Dx Ss All Levels,07/05/2016 21:55:31 +0000,1822.0,"[Dustforce, Dx, Ss, All, Levels]",[],All Levels,Dustforce Dx Ss
1456,NaN,01/09/2017 19:41:00 +0000,Mario Paint Gnat Attack Level 3,01/09/2017 19:27:00 +0000,1975.0,"[Mario, Paint, Gnat, Attack, Level, 3]",[],Level 3,Mario Paint Gnat Attack
1461,NaN,01/09/2017 23:07:32 +0000,Super Monkey Ball 2 Story Mode All Levels,01/09/2017 22:21:58 +0000,1979.0,"[Super, Monkey, Ball, 2, Story, Mode, All, Lev...",[],All Levels Story Mode,Super Monkey Ball 2
1493,NaN,01/11/2017 01:45:56 +0000,Super Mario Bros.: The Lost Levels Any% 8-4,01/11/2017 01:09:56 +0000,2013.0,"[Super, Mario, Bros.:, The, Lost, Levels, Any%...",[],Any%,Super Mario Bros.: The Lost Levels
1511,NaN,01/11/2017 13:44:00 +0000,Seum: Speedrunners From Hell Speedrun Mode: Al...,01/11/2017 13:16:00 +0000,1966.0,"[Seum:, Speedrunners, From, Hell, Speedrun, Mo...",[],All Levels Speedrun Mode,Seum:
1596,NaN,01/14/2017 19:53:05 +0000,Bonus: Super Mario Bros.: The Lost Levels Any%...,01/14/2017 19:08:05 +0000,2114.0,"[Bonus:, Super, Mario, Bros.:, The, Lost, Leve...",[],Any% 2 Players 1 Controller,Bonus: Super Mario Bros.: The Lost Levels
1637,NaN,07/04/2017 05:28:00 +0000,Donkey Kong 64 No Levels Early,07/04/2017 02:56:00 +0000,2163.0,"[Donkey, Kong, 64, No, Levels, Early]",[],No Levels Early,Donkey Kong 64
1761,NaN,09/02/2017 14:09:54 +0000,Super Lovely Planet All Levels,09/02/2017 13:52:54 +0000,2606.0,"[Super, Lovely, Planet, All, Levels]",[],All Levels,Super Lovely Planet
1764,NaN,09/02/2017 16:24:53 +0000,Bastion Ng All Story Levels,09/02/2017 15:15:54 +0000,2609.0,"[Bastion, Ng, All, Story, Levels]",[],All Story Levels,Bastion Ng
1806,NaN,01/08/2018 09:48:00 +0000,Battleblock Theater Any% No Level Skips,01/08/2018 08:15:00 +0000,2655.0,"[Battleblock, Theater, Any%, No, Level, Skips]",[],Any% No Level Skips,Battleblock Theater
1835,NaN,01/09/2018 11:56:00 +0000,Super Lovely Planet All Levels,01/09/2018 11:30:00 +0000,2687.0,"[Super, Lovely, Planet, All, Levels]",[],All Levels,Super Lovely Planet
1938,NaN,01/13/2018 18:08:00 +0000,Diablo Any% Level 1 Sorcerer,01/13/2018 17:18:00 +0000,2791.0,"[Diablo, Any%, Level, 1, Sorcerer]",[],Any% Level 1 Sorcerer,Diablo
1981,NaN,06/25/2018 22:57:00 +0000,Dustforce Dx Any% All Levels (Ng+) Race,06/25/2018 22:00:00 +0000,2993.0,"[Dustforce, Dx, Any%, All, Levels, (Ng+), Race]",[],Any% All Levels Ng+ Race,Dustforce Dx
2017,NaN,06/27/2018 15:56:00 +0000,Super Monkey Ball 2 Story Mode All Levels,06/27/2018 15:11:00 +0000,3119.0,"[Super, Monkey, Ball, 2, Story, Mode, All, Lev...",[],All Levels Story Mode,Super Monkey Ball 2
2018,NaN,06/27/2018 16:36:00 +0000,Super Monkey Ball 2: Monkeyed Ball Story Mode ...,06/27/2018 15:56:00 +0000,3090.0,"[Super, Monkey, Ball, 2:, Monkeyed, Ball, Stor...",[],All Levels Race Story Mode,Super Monkey Ball 2: Monkeyed Ball
2025,NaN,06/27/2018 20:38:00 +0000,Sublevel Zero Redux Normal Any%,06/27/2018 19:57:00 +0000,3037.0,"[Sublevel, Zero, Redux, Normal, Any%]",[],Any% Normal Any,Sublevel Zero Redux
2078,NaN,06/30/2018 00:19:23 +0000,Kingdom Hearts Hd 1.5 Remix (Kh1fm) Any% (Leve...,06/29/2018 20:51:23 +0000,3092.0,"[Kingdom, Hearts, Hd, 1.5, Remix, (Kh1fm), Any...",[],Any% Proud Mode,Kingdom Hearts Hd 1.5 Remix (Kh1fm)
2097,NaN,06/30/2018 21:12:00 +0000,Super Mario Maker 3v3 Blind Level Race,06/30/2018 19:40:50 +0000,3113.0,"[Super, Mario, Maker, 3v3, Blind, Level, Race]",[],Blind Race Level Race,Super Mario Maker 3v3

In [52]:
search('beat ', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
1276,NaN,07/04/2016 14:25:00 +0000,Sparkster Beat The Game Normal,07/04/2016 13:51:00 +0000,1790.0,"[Sparkster, Beat, The, Game, Normal]",[],Beat The Game Normal,Sparkster
1393,NaN,07/08/2016 14:31:00 +0000,Ultraman Ball Beat The Game,07/08/2016 14:12:00 +0000,1907.0,"[Ultraman, Ball, Beat, The, Game]",[],Beat The Game,Ultraman Ball
1469,NaN,01/10/2017 06:47:00 +0000,Decap Attack Beat The Game,01/10/2017 06:07:00 +0000,1988.0,"[Decap, Attack, Beat, The, Game]",[],Beat The Game,Decap Attack
1668,NaN,07/05/2017 14:59:00 +0000,Kyatto Ninden Teyandee Beat The Game,07/05/2017 14:42:00 +0000,2194.0,"[Kyatto, Ninden, Teyandee, Beat, The, Game]",[],Beat The Game,Kyatto Ninden Teyandee
1694,NaN,07/06/2017 13:06:00 +0000,The Addams Family: Pugsley's Scavenger Hunt Be...,07/06/2017 12:43:00 +0000,2219.0,"[The, Addams, Family:, Pugsley's, Scavenger, H...",[],Beat The Game,
1889,NaN,01/11/2018 13:16:00 +0000,Titenic Beat The Game,01/11/2018 12:50:00 +0000,2741.0,"[Titenic, Beat, The, Game]",[],Beat The Game,Titenic
2019,NaN,06/27/2018 17:04:00 +0000,Spider-Man: Web Of Fire Beat The Game,06/27/2018 16:36:00 +0000,3030.0,"[Spider-Man:, Web, Of, Fire, Beat, The, Game]",[],Beat The Game,Spider-Man: Web Of Fire
2037,NaN,06/28/2018 08:43:00 +0000,Live Beat The Game,06/28/2018 08:30:00 +0000,3049.0,"[Live, Beat, The, Game]",[],Beat The Game,Live
2093,NaN,06/30/2018 15:05:00 +0000,Kirby's Dream Land Beat Extra Mode,06/30/2018 14:42:00 +0000,3109.0,"[Kirby's, Dream, Land, Beat, Extra, Mode]",[],Extra Mode,Kirby's Dream Land Beat

In [67]:
search('warpless', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
433,warpless,07/29/2013 06:24:00 +0000,Super Mario Bros.,07/29/2013 05:50:58 +0000,194.0,"[Super, Mario, Bros.]",[warpless],warpless,Super Mario Bros.
503,Race. Bidding war for any% and warpless.,01/07/2014 15:51:00 +0000,Battletoads,01/07/2014 15:11:00 +0000,415.0,[Battletoads],"[Race., Bidding, war, for, any%, and, warpless.]",any% warpless Race,Battletoads
513,Warpless. Donations for a warps run.,01/07/2014 22:42:00 +0000,Super Mario Bros.,01/07/2014 22:15:00 +0000,427.0,"[Super, Mario, Bros.]","[Warpless., Donations, for, a, warps, run.]",Warpless,Super Mario Bros.
534,any% donations for warpless,01/09/2014 01:52:00 +0000,Donkey Kong Country 3,01/09/2014 00:52:00 +0000,445.0,"[Donkey, Kong, Country, 3]","[any%, , donations, for, warpless]",any% warpless,Donkey Kong Country 3
746,Warpless,06/28/2014 00:30:00 +0000,Super Mario Bros. 2 (U.S.),06/27/2014 23:48:00 +0000,658.0,"[Super, Mario, Bros., 2, (U.S.)]",[Warpless],Warpless,Super Mario Bros. 2 (U.S.)
747,Warpless,06/28/2014 01:34:00 +0000,Super Mario Bros. 3,06/28/2014 00:30:00 +0000,659.0,"[Super, Mario, Bros., 3]",[Warpless],Warpless,Super Mario Bros. 3
814,co-op donations for warpless run,01/06/2015 12:19:00 +0000,Battletoads,01/06/2015 11:37:00 +0000,758.0,[Battletoads],"[co-op, , donations, for, warpless, run]",warpless co-op,Battletoads
1071,Warpless Luigi Worlds 1 through D,07/31/2015 22:24:00 +0000,Super Mario Bros: The Lost Levels,07/31/2015 21:29:00 +0000,1259.0,"[Super, Mario, Bros:, The, Lost, Levels]","[Warpless, Luigi, , Worlds, 1, through, D]",Warpless,Super Mario Bros: The Lost Levels
1072,Warpless race incentive for 100%,08/01/2015 00:05:00 +0000,Super Mario Bros. 3,07/31/2015 22:24:00 +0000,1260.0,"[Super, Mario, Bros., 3]","[Warpless, race, , incentive, for, 100%]",100% Warpless race,Super Mario Bros. 3
1274,NaN,07/04/2016 13:16:00 +0000,Claymates Any% Warpless,07/04/2016 12:24:00 +0000,1788.0,"[Claymates, Any%, Warpless]",[],Any% Warpless,Claymates
1357,NaN,07/07/2016 12:54:00 +0000,Zelda Ii: The Adventure Of Link Any% Warpless,07/07/2016 11:40:00 +0000,1873.0,"[Zelda, Ii:, The, Adventure, Of, Link, Any%, W...",[],Any% Warpless,Zelda Ii: The Adventure Of Link
1465,NaN,01/10/2017 04:42:00 +0000,Blaster Master Any% Warpless,01/10/2017 03:52:00 +0000,1984.0,"[Blaster, Master, Any%, Warpless]",[],Any% Warpless,Blaster Master
1491,NaN,01/11/2017 00:53:06 +0000,Super Mario Bros. Warpless,01/11/2017 00:21:00 +0000,2012.0,"[Super, Mario, Bros., Warpless]",[],Warpless,Super Mario Bros.
1577,NaN,01/13/2017 20:34:56 +0000,Crash Team Racing Any% Warpless,01/13/2017 19:32:00 +0000,2095.0,"[Crash, Team, Racing, Any%, Warpless]",[],Any% Warpless,Crash Team Racing
1729,NaN,07/08/2017 01:55:00 +0000,Super Mario Series Warpless Relay Race Warples...,07/07/2017 22:49:36 +0000,2255.0,"[Super, Mario, Series, Warpless, Relay, Race, ...",[],Warpless Relay Race,Super Mario Series
1769,NaN,09/02/2017 19:18:43 +0000,Battletoads Any% Warpless,09/02/2017 18:41:54 +0000,2614.0,"[Battletoads, Any%, Warpless]",[],Any% Warpless,Battletoads
1788,NaN,09/03/2017 20:04:04 +0000,Super Mario World 2: Yoshi's Island Any% Warpl...,09/03/2017 18:09:04 +0000,2633.0,"[Super, Mario, World, 2:, Yoshi's, Island, Any...",[],Any% Warpless Race,Super Mario World 2: Yoshi's Island
1817,NaN,01/08/2018 16:49:00 +0000,Donkey Kong Country 2: Diddy's Kong Quest Any%...,01/08/2018 15:35:00 +0000,2667.0,"[Donkey, Kong, Country, 2:, Diddy's, Kong, Que...",[],Any% Warpless Race,Donkey Kong Country 2: Diddy's Kong Quest
1868,NaN,01/10/2018 18:41:00 +0000,Battletoads Any% Warpless,01/10/2018 17:51:00 +0000,2719.0,"[Battletoads, Any%, Warpless]",[],Any% Warpless,Battletoads
1870,NaN,01/10/2018 20:08:00 +0000,Metroid All Bosses Warpless,01/10/2018 19:18:00 +0000,2721.0,"[Metroid, All, Bosses, Warpless]",[],Warpless All Bosses Warpless,Metroid
1874,NaN,01/11/2018 02:26:24 +0000,Super Mario World 2: Yoshi's Island Any% Warpl...,01/11/2018 00:13:00 +0000,2725.0,"[Super, Mario, World, 2:, Yoshi's, Island, Any...",[],Any% Warpless Race,Super Mario World 2: Yoshi's Island
2029,NaN,06/28/2018 02:48:00 +0000,Super Mario 3d Land Warpless,06/28/2018 01:17:00 +0000,3041.0,"[Super, Mario, 3d, Land, Warpless]",[],Warpless,Super Mario 3d Land
2058,NaN,06/29/2018 01:58:00 +0000,Super Mario Bros. Warpless,06/29/2018 00:57:30 +0000,3072.0,"[Super, Mario, Bros., Warpless]",[],Warpless,Super Mario Bros.
2095,NaN,06/30/2018 17:31:57 +0000,New Super Mario Bros. 2 Warpless,06/30/2018 16:08:54 +0000,3111.0,"[New, Super, Mario, Bros., 2, Warpless]",[],Warpless,New Super Mario Bros. 2

In [95]:
search('track', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
253,Soundtrack bidding war donations for Good Fut...,01/07/2013 19:48:07 +0000,Sonic Cd,01/07/2013 19:21:00 +0000,18.0,"[Sonic, Cd]","[Soundtrack, bidding, war, , donations, for, G...",,Sonic Cd
751,16 star run. Go to donation tracker to see how...,06/28/2014 07:42:57 +0000,Super Mario 64,06/28/2014 05:54:00 +0000,704.0,"[Super, Mario, 64]","[16, star, run., Go, to, donation, tracker, to...",16 star,Super Mario 64
772,New 16 Tracks,01/05/2015 01:53:00 +0000,Mario Kart Wii,01/05/2015 00:45:00 +0000,713.0,"[Mario, Kart, Wii]","[New, 16, Tracks]",16 Tracks,Mario Kart Wii
1238,Donation Incentive: Character Choice Bidwar,01/09/2016 20:01:27 +0000,Mario Kart 8 200cc 32 Tracks Hard Cpu,01/09/2016 18:33:27 +0000,1739.0,"[Mario, Kart, 8, 200cc, 32, Tracks, Hard, Cpu]","[Donation, Incentive:, Character, Choice, Bidwar]",Hard Cpu 32 Tracks,Mario Kart 8 200cc
1368,NaN,07/08/2016 00:18:00 +0000,Trials Fusion Community/Ninja/Retro Track Show...,07/07/2016 22:29:00 +0000,1884.0,"[Trials, Fusion, Community/Ninja/Retro, Track,...",[],Community/Ninja/Retro Track Showcase,Trials Fusion
1395,NaN,07/08/2016 15:37:00 +0000,Kirby Air Ride Air Ride All Tracks,07/08/2016 15:09:00 +0000,1909.0,"[Kirby, Air, Ride, Air, Ride, All, Tracks]",[],All Tracks,Kirby Air Ride Air Ride
1707,NaN,07/07/2017 04:34:00 +0000,Mario Kart Wii Nitro Tracks (No Skips),07/07/2017 02:33:59 +0000,2232.0,"[Mario, Kart, Wii, Nitro, Tracks, (No, Skips)]",[],No Skips Tracks,Mario Kart Wii Nitro
1800,NaN,01/08/2018 02:05:00 +0000,F-Zero Gx All Tracks Time Attack (Max Speed),01/08/2018 00:36:32 +0000,2648.0,"[F-Zero, Gx, All, Tracks, Time, Attack, (Max, ...",[],All Tracks Time Attack,F-Zero Gx
2061,NaN,06/29/2018 06:38:00 +0000,Mario Kart 8 Deluxe 32 Tracks 200cc Items,06/29/2018 04:49:00 +0000,3075.0,"[Mario, Kart, 8, Deluxe, 32, Tracks, , 200cc, ...",[],32 Tracks,Mario Kart 8 Deluxe

In [138]:
search('showcase', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
1097,Donation Incentive: Music Level Showcase (0:05),01/03/2016 21:35:00 +0000,Rayman Legends Any%,01/03/2016 19:37:00 +0000,1599.0,"[Rayman, Legends, Any%]","[Donation, Incentive:, Music, Level, Showcase,...",Any% Level Showcase,Rayman Legends
1152,Donation Incentive: Showcase obsolete 'pigflyi...,01/06/2016 09:54:41 +0000,Amnesia: A Machine For Pigs Any%,01/06/2016 09:19:41 +0000,1654.0,"[Amnesia:, A, Machine, For, Pigs, Any%]","[Donation, Incentive:, Showcase, obsolete, 'pi...",Any%,Amnesia: A Machine For Pigs
1192,NaN,01/07/2016 13:07:14 +0000,Age Of Empires Il Showcase,01/07/2016 11:53:14 +0000,1694.0,"[Age, Of, Empires, Il, Showcase]",[],,Age Of Empires Il Showcase
1202,Donation Incentive: 'Third Person Cutscene Sho...,01/07/2016 21:14:27 +0000,Mirror's Edge Any%,01/07/2016 20:19:27 +0000,1704.0,"[Mirror's, Edge, Any%]","[Donation, Incentive:, 'Third, Person, Cutscen...",Any%,Mirror's Edge
1203,NaN,01/07/2016 22:14:27 +0000,Stepmania Showcase,01/07/2016 21:14:27 +0000,1705.0,"[Stepmania, Showcase]",[],,Stepmania Showcase
1210,Donation Incentives: Glitch Showcase (0:05) c...,01/08/2016 08:21:27 +0000,Paper Mario All Cards,01/08/2016 05:00:27 +0000,1712.0,"[Paper, Mario, All, Cards]","[Donation, Incentives:, Glitch, Showcase, (0:0...",All Cards Glitch Showcase,Paper Mario
1214,Donation Incentives: Name Bidwar for the Boy ...,01/08/2016 14:45:27 +0000,Secret Of Mana Any% 1p2c,01/08/2016 12:22:27 +0000,1716.0,"[Secret, Of, Mana, Any%, 1p2c]","[Donation, Incentives:, Name, Bidwar, for, the...",Any% 1p2c Glitch Showcase,Secret Of Mana
1220,Bonus Incentive: Pokemon Blue (Glitch Showcase...,01/08/2016 20:56:27 +0000,Pokemon Blue Glitch Showcase,01/08/2016 20:24:27 +0000,1721.0,"[Pokemon, Blue, Glitch, Showcase]","[Bonus, Incentive:, Pokemon, Blue, (Glitch, Sh...",Glitch Showcase,Pokemon Blue
1230,Donation Incentive: Glitch Showcase (0:07),01/09/2016 04:31:27 +0000,The Legend Of Zelda: Ocarina Of Time / Master ...,01/09/2016 02:12:27 +0000,1731.0,"[The, Legend, Of, Zelda:, Ocarina, Of, Time, /...","[Donation, Incentive:, Glitch, Showcase, (0:07)]",All Dungeons Glitch Showcase,The Legend Of Zelda: Ocarina Of Time / Master ...
1368,NaN,07/08/2016 00:18:00 +0000,Trials Fusion Community/Ninja/Retro Track Show...,07/07/2016 22:29:00 +0000,1884.0,"[Trials, Fusion, Community/Ninja/Retro, Track,...",[],Community/Ninja/Retro Track Showcase,Trials Fusion
1871,NaN,01/10/2018 21:04:00 +0000,Strider Live Tutorial Showcase,01/10/2018 20:08:00 +0000,2722.0,"[Strider, Live, Tutorial, Showcase]",[],,Strider Live Tutorial Showcase

In [139]:
search('exhibition', new_runs)

,Description,End Time,Name,Start Time,run_id,name_token,desc_token,category,new_Name
863,This will melt your mind.,01/08/2015 02:59:00 +0000,Tetris: The Grandmaster Exhibition,01/08/2015 01:07:00 +0000,792.0,"[Tetris:, The, Grandmaster, Exhibition]","[This, will, melt, your, mind.]",,Tetris: The Grandmaster Exhibition
915,Race. Donation incentive for glitch exhibition,01/10/2015 02:42:00 +0000,The Legend Of Zelda: Majora's Mask,01/10/2015 00:42:00 +0000,851.0,"[The, Legend, Of, Zelda:, Majora's, Mask]","[Race., Donation, incentive, for, glitch, exhi...",Race glitch exhibition,The Legend Of Zelda: Majora's Mask
1367,NaN,07/07/2016 22:29:00 +0000,Tetris: The Grand Master Series Exhibition Exh...,07/07/2016 19:59:00 +0000,1883.0,"[Tetris:, The, Grand, Master, Series, Exhibiti...",[],,Tetris: The Grand Master Series Exhibition Exh...
1409,NaN,07/09/2016 07:49:00 +0000,The Legend Of Zelda: Ocarina Of Time Glitch Ex...,07/09/2016 07:10:00 +0000,1922.0,"[The, Legend, Of, Zelda:, Ocarina, Of, Time, G...",[],Glitch Exhibition,The Legend Of Zelda: Ocarina Of Time